EnsureSConsVersion(0, 98, 0)

# FIXME Should get the project base in a more sensible fashion
import os.path
PROJECT_BASE = os.path.join('..')

THIRDPARTY_BASE = os.path.join(PROJECT_BASE, '..', '..', 'thirdparty')


class Env(Environment):
  def __init__(self, *args, **kw):
    self.INCLUDES = []
    self.LIBPATHS = []
    self.LIBS = []
    Environment.__init__(self, *args, **kw)

  def sconscript(self, thirdparty, **kw):
    import os.path
    thirdparty = [os.path.join(THIRDPARTY_BASE, p) for p in thirdparty]

    sconscript_files = [os.path.join(p, 'scons', 'SConscript') for p in thirdparty]
    SConscript(sconscript_files, **kw)

  def appendPaths(self, scons, include_dir = '.'):
    import os.path
    self.LIBPATHS.append(scons)
    self.INCLUDES.append(os.path.join(os.path.dirname(scons), include_dir))

env = Env()

SOURCES = [
  'al/Listener.cpp',
  'al/Buffer.cpp',
  'al/Source.cpp',
  'al/Device.cpp',
  'al/Debug.cpp',
  'al/Context.cpp',

  'math/RectPacker.cpp',

  'platform/Platform_Linux.cpp',
  'platform/Platform.cpp',

  'audio/Source.cpp',
  'audio/Engine.cpp',
  'audio/VorbisFile.cpp',

  'event/EventDispatcher.cpp',

  'font/freetype/Library.cpp',
  'font/freetype/Face.cpp',
  'font/Model.cpp',
  'font/TrueTypeFont.cpp',

  'lua/ErrorHandler.cpp',
  'lua/State.cpp',
  'lua/BindAll.cpp',
  'lua/bindings/LostGLFrameBuffer.cpp',
  'lua/bindings/LostGLTexture.cpp',
  'lua/bindings/LostModelLSystemRenderer.cpp',
  'lua/bindings/LostResourceFile.cpp',
  'lua/bindings/LostFontFreetypeLibrary.cpp',
  'lua/bindings/LostGLContext.cpp',
  'lua/bindings/LostCommonColor.cpp',
  'lua/bindings/LostResourceLoader.cpp',
  'lua/bindings/LostApplicationKeyEvent.cpp',
  'lua/bindings/LostLGLLGL.cpp',
  'lua/bindings/LostMathVec4.cpp',
  'lua/bindings/LostEventEventDispatcher.cpp',
  'lua/bindings/LostModelObjRenderer.cpp',
  'lua/bindings/LostApplicationTimer.cpp',
  'lua/bindings/LostModelObjMaterial.cpp',
  'lua/bindings/LostApplicationApplication.cpp',
  'lua/bindings/LostCommonLog.cpp',
  'lua/bindings/LostModelObjParser.cpp',
  'lua/bindings/LostGLRenderBuffer.cpp',
  'lua/bindings/LostFontModel.cpp',
  'lua/bindings/LostMathVec3.cpp',
  'lua/bindings/LostApplicationTouchEvent.cpp',
  'lua/bindings/LostGLGL.cpp',
  'lua/bindings/LostApplicationTimerEvent.cpp',
  'lua/bindings/LostModelMesh.cpp',
  'lua/bindings/LostGLMesh.cpp',
  'lua/bindings/LostBitmapBitmap.cpp',
  'lua/bindings/LostApplicationAccelerometerEvent.cpp',
  'lua/bindings/LostPlatformPlatform.cpp',
  'lua/bindings/LostCommonFpsMeter.cpp',
  'lua/bindings/LostFontTrueTypeFont.cpp',
  'lua/bindings/LostMathVec2.cpp',
  'lua/bindings/LostApplicationApplicationEvent.cpp',
  'lua/bindings/LostGLState.cpp',
  'lua/bindings/LostApplicationResizeEvent.cpp',
  'lua/bindings/LostGLUtils.cpp',
  'lua/bindings/LostApplicationMouseEvent.cpp',
  'lua/bindings/LostGLDraw.cpp',
  'lua/bindings/LostCommonDisplayAttributes.cpp',
  'lua/bindings/LostLuaState.cpp',
  'lua/bindings/LostLSystemLSystem.cpp',
  'lua/bindings/LostCameraCamera.cpp',
  'lua/bindings/LostEventEvent.cpp',
  'lua/bindings/LostMathRect.cpp',
  'lua/bindings/LostModelLSystemGenerator.cpp',
  'lua/BindingHelpers.cpp',
  'lua/ModuleLoader.cpp',

  'application/Timer.cpp',
  'application/glfw/TimerManager.cpp',
  'application/glfw/Timer.cpp',
  'application/glfw/Application.cpp',
  'application/glfw/ApplicationAdapter.cpp',
  'application/Application.cpp',

  'obj/Parser.cpp',

  'camera/Camera.cpp',
  'camera/Camera2D.cpp',

  'bitmap/Bitmap.cpp',
  'bitmap/Packer.cpp',

  'common/Profiler.cpp',
  'common/FpsMeter.cpp',
  'common/Logger.cpp',

  'gl/State.cpp',
  'gl/Utils.cpp',
  'gl/Texture.cpp',
  'gl/Context.cpp',
]

HEADERS = [
  'al/Source.h',
  'al/Buffer.h',
  'al/al.h',
  'al/Debug.h',
  'al/Listener.h',
  'al/Context.h',
  'al/Device.h',

  'model/Mesh.h',
  'model/lsystem/Renderer.h',
  'model/lsystem/Generator.h',
  'model/Vertex.h',
  'model/obj/Renderer.h',
  'model/obj/Parser.h',
  'model/obj/Material.h',

  'lsystem/LSystem.h',

  'math/Matrix.h',
  'math/Vec3.h',
  'math/Vec2.h',
  'math/Vec4.h',
  'math/AABB.h',
  'math/RectPacker.h',
  'math/Rect.h',
  'math/lmath.h',
  'math/Generator.h',

  'platform/Platform.h',

  'audio/Engine.h',
  'audio/Source.h',
  'audio/VorbisFile.h',

  'resource/Repository.h',
  'resource/Loader.h',
  'resource/File.h',
  'resource/ApplicationResourceRepository.h',
  'resource/DefaultLoader.h',

  'event/Event.h',
  'event/Receive.h',
  'event/EventDispatcher.h',

  'font/freetype/Face.h',
  'font/freetype/Library.h',
  'font/TrueTypeFont.h',
  'font/Model.h',

  'lua/ErrorHandler.h',
  'lua/bindings/LostApplicationApplicationEvent.h',
  'lua/bindings/LostMathVec2.h',
  'lua/bindings/LostGLContext.h',
  'lua/bindings/LostApplicationMouseEvent.h',
  'lua/bindings/LostCommonDisplayAttributes.h',
  'lua/bindings/LostGLUtils.h',
  'lua/bindings/LostLuaState.h',
  'lua/bindings/LostApplicationKeyEvent.h',
  'lua/bindings/LostMathVec4.h',
  'lua/bindings/LostLSystemLSystem.h',
  'lua/bindings/LostGLDraw.h',
  'lua/bindings/LostCommonLog.h',
  'lua/bindings/LostPlatformPlatform.h',
  'lua/bindings/LostModelObjMaterial.h',
  'lua/bindings/LostGLMesh.h',
  'lua/bindings/LostApplicationTouchEvent.h',
  'lua/bindings/LostModelObjRenderer.h',
  'lua/bindings/LostModelObjParser.h',
  'lua/bindings/LostGLTexture.h',
  'lua/bindings/LostApplicationApplication.h',
  'lua/bindings/LostModelLSystemGenerator.h',
  'lua/bindings/LostMathVec3.h',
  'lua/bindings/LostResourceFile.h',
  'lua/bindings/LostApplicationAccelerometerEvent.h',
  'lua/bindings/LostApplicationTimer.h',
  'lua/bindings/LostFontFreetypeLibrary.h',
  'lua/bindings/LostFontTrueTypeFont.h',
  'lua/bindings/LostEventEvent.h',
  'lua/bindings/LostCommonColor.h',
  'lua/bindings/LostModelLSystemRenderer.h',
  'lua/bindings/LostGLState.h',
  'lua/bindings/LostCameraCamera.h',
  'lua/bindings/LostLGLLGL.h',
  'lua/bindings/LostGLRenderBuffer.h',
  'lua/bindings/LostResourceLoader.h',
  'lua/bindings/LostMathRect.h',
  'lua/bindings/LostBitmapBitmap.h',
  'lua/bindings/LostApplicationResizeEvent.h',
  'lua/bindings/LostGLFrameBuffer.h',
  'lua/bindings/LostFontModel.h',
  'lua/bindings/LostApplicationTimerEvent.h',
  'lua/bindings/LostModelMesh.h',
  'lua/bindings/LostGLGL.h',
  'lua/bindings/LostEventEventDispatcher.h',
  'lua/bindings/LostCommonFpsMeter.h',
  'lua/ModuleLoader.h',
  'lua/State.h',
  'lua/lua.h',
  'lua/BindAll.h',
  'lua/EventCast.h',

  'application/Config.h',
  'application/KeySym.h',
  'application/MouseEvent.h',
  'application/Application.h',
  'application/Timer.h',
  'application/iphone/LostApplicationHelpers.h',
  'application/iphone/LostAppController.h',
  'application/iphone/LostGlView.h',
  'application/AccelerometerEvent.h',
  'application/ApplicationEvent.h',
  'application/MouseButton.h',
  'application/TimerEvent.h',
  'application/KeyEvent.h',
  'application/glfw/TimerManager.h',
  'application/glfw/ApplicationAdapter.h',
  'application/ResizeEvent.h',
  'application/TouchEvent.h',
  'application/MainLoop.h',

  'obj/Face.h',
  'obj/Vertex.h',
  'obj/Scene.h',
  'obj/Parser.h',

  'camera/Camera2D.h',
  'camera/Camera.h',

  'bitmap/Packer.h',
  'bitmap/Bitmap.h',

  'lgl/lglu.h',
  'lgl/lgl_gl.h',
  'lgl/lgl.h',
  'lgl/lgl_gles.h',

  'common/DisplayAttributes.h',
  'common/SpiritHelpers.h',
  'common/NullDeleter.h',
  'common/Color.h',
  'common/Logger.h',
  'common/Profiler.h',
  'common/FpsMeter.h',

  'gl/PushClientAttrib.h',
  'gl/Mesh.h',
  'gl/ArrayBuffer.h',
  'gl/ShaderHelper.h',
  'gl/Shader.h',
  'gl/Buffer.h',
  'gl/ElementArrayBuffer.h',
  'gl/Texture.h',
  'gl/VertexShader.h',
  'gl/DisplayList.h',
  'gl/FragmentShader.h',
  'gl/PushAttrib.h',
  'gl/Utils.h',
  'gl/Scissor.h',
  'gl/gl.h',
  'gl/Context.h',
  'gl/State.h',
  'gl/RenderBuffer.h',
  'gl/ShaderProgram.h',
  'gl/TraitsSelector.h',
  'gl/FrameBuffer.h',
  'gl/TypedBuffer.h',
]

TEST_SOURCES = [
#  'test/TestEngine.cpp',
  'test/TestProfiler.cpp',
#  'test/TestEventDispatcher.cpp',
  'test/TestLostMathMatrix.cpp',
  'test/TestEvent.cpp',
  'test/TestLostMathVec4.cpp',
  'test/TestCompileLostMathVec2.cpp',
#  'test/TestGlUtils.cpp',
  'test/TestPlatform.cpp',
  'test/main.cpp',
]

THIRDPARTY = [
  os.path.join('boost', 'boost_1_36_0'),
]



SOURCES = [os.path.join(PROJECT_BASE, 'lost', s) for s in SOURCES]
HEADERS = [os.path.join(PROJECT_BASE, 'lost', h) for h in HEADERS]
TEST_SOURCES = [os.path.join(PROJECT_BASE, 'lost', s) for s in TEST_SOURCES]

INCLUDES = [
  PROJECT_BASE,
  os.path.join(THIRDPARTY_BASE, 'OpenAL', 'OpenAL_1_1', 'include'),
  os.path.join(THIRDPARTY_BASE, 'stb', 'stb_vorbis_0_99996'),
  os.path.join(THIRDPARTY_BASE, 'stb', 'stb_image_1_14'),
  os.path.join(THIRDPARTY_BASE, 'freetype2', 'freetype_2_3_7', 'include'),
  os.path.join(THIRDPARTY_BASE, 'glee', 'glee_5_21', 'include'),
  os.path.join(THIRDPARTY_BASE, 'OpenGL', 'include'),
  os.path.join(THIRDPARTY_BASE, 'glfw', 'glfw_2_6', 'include'),
  os.path.join(THIRDPARTY_BASE, 'lua', 'lua_5_1_4', 'include'),
  os.path.join(THIRDPARTY_BASE, 'luabind', 'luabind_0_8', 'include'),
  os.path.join(THIRDPARTY_BASE, 'hashlib++', 'hashlib++_0_3_1'),
  os.path.join(THIRDPARTY_BASE, 'UnitTest++', 'include'),
]

env.sconscript(THIRDPARTY, exports = ['env'])

lostengine = StaticLibrary('lostengine', SOURCES,
    CPPPATH = [PROJECT_BASE] + env.INCLUDES + INCLUDES)

unittestpp = StaticLibrary('unittestpp', [
    # FIXME FUGLY, needs fix, but I don't care right now
    '../../../thirdparty/UnitTest++/include/DeferredTestReporter.cpp',
    '../../../thirdparty/UnitTest++/include/TimeConstraint.cpp',
    '../../../thirdparty/UnitTest++/include/Posix/TimeHelpers.cpp',
    '../../../thirdparty/UnitTest++/include/Posix/SignalTranslator.cpp',
    '../../../thirdparty/UnitTest++/include/TestRunner.cpp',
    '../../../thirdparty/UnitTest++/include/DeferredTestResult.cpp',
    '../../../thirdparty/UnitTest++/include/TestReporter.cpp',
    '../../../thirdparty/UnitTest++/include/XmlTestReporter.cpp',
    '../../../thirdparty/UnitTest++/include/AssertException.cpp',
    '../../../thirdparty/UnitTest++/include/ReportAssert.cpp',
    '../../../thirdparty/UnitTest++/include/TestResults.cpp',
    '../../../thirdparty/UnitTest++/include/TestReporterStdout.cpp',
    '../../../thirdparty/UnitTest++/include/TestList.cpp',
    '../../../thirdparty/UnitTest++/include/Test.cpp',
    '../../../thirdparty/UnitTest++/include/MemoryOutStream.cpp',
    '../../../thirdparty/UnitTest++/include/TestDetails.cpp',
    '../../../thirdparty/UnitTest++/include/Checks.cpp',

# dont' need the unit test lib's tests
#    '../../../thirdparty/UnitTest++/include/tests/TestTimeConstraint.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestMemoryOutStream.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestChecks.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestAssertHandler.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTimeConstraintMacro.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/Main.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTestMacros.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestDeferredTestReporter.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTestSuite.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTestResults.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestXmlTestReporter.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTestRunner.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestCheckMacros.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTest.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestTestList.cpp',
#    '../../../thirdparty/UnitTest++/include/tests/TestUnitTest++.cpp',

  ])

Program('tests', TEST_SOURCES,
    CPPPATH = [PROJECT_BASE] + env.INCLUDES + INCLUDES,
    LIBS = [lostengine, unittestpp] + env.LIBS)



